/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    projects: Project;
    media: Media;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    site: Site;
    'home-page': HomePage;
    'freelance-page': FreelancePage;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  description: {
    [k: string]: unknown;
  }[];
  projectUrl: string;
  copmanyName: string;
  copmanyUrl: string;
  stamp?: string | null;
  technologies: (
    | 'Angular'
    | 'Node.js'
    | 'NestJs'
    | 'MongoDB'
    | 'Docker'
    | 'Kubernetes'
    | 'iOS (Swift)'
    | 'Android (Kotlin)'
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: string;
  nav: {
    freelance: string;
    github: string;
    languageAria: string;
  };
  footer: {
    text: string;
  };
  stack?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  meta: {
    title: string;
    description: string;
  };
  intro: {
    status: string;
    polaroidAlt: string;
    polaroidCaption: string;
    currentlyKicker: string;
    currentlyRole: string;
    currentlySuffix: string;
    currentlyAt: string;
    asideKicker: string;
    asideText: string;
    freelanceCta: string;
    scrollHint: string;
    scrollAria: string;
  };
  projects: {
    titlePrefix: string;
    titleItalic: string;
    titleMarker: string;
    ledePrefix: string;
    ledeItalic: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "freelance-page".
 */
export interface FreelancePage {
  id: string;
  meta: {
    title: string;
    description: string;
  };
  hero: {
    availabilityTag: string;
    titleLine1: string;
    titleScript: string;
    titleLine3: string;
    pitchPrefix: string;
    pitchMarker: string;
    pitchSuffix: string;
    pitchItalic: string;
    ctaPrimary: string;
    ctaSecondary: string;
    availableLabel: string;
    availableSub: string;
    basedInKicker: string;
    basedInValue: string;
    workingWithKicker: string;
    workingWithValue: string;
    replyTimeKicker: string;
    replyTimeValue: string;
  };
  chapter01: {
    titlePrefix: string;
    titleMarker: string;
    titleSuffix: string;
    services?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  chapter02: {
    titlePrefix: string;
    titleScript: string;
    titleSuffix: string;
    lede: string;
  };
  chapter03: {
    titlePrefix: string;
    titleMarker: string;
    text: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
