name: build & push & deploy client

on:
    push:
        branches:
            - 'release/server'
env:
    # Use docker.io for Docker Hub if empty
    REGISTRY: ghcr.io
    # github.repository as <account>/<repo>
    IMAGE_NAME: ${{ github.repository }}-server

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              id: build-and-push
              uses: docker/build-push-action@v6
              with:
                  context: '{{defaultContext}}:server'
                  push: true
                  tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    deploy:
        needs: docker
        name: deploy image
        runs-on: ubuntu-latest
        steps:
            - name: install ssh keys
              uses: fifsky/ssh-action@master
              with:
                  command: 'cd ${{ secrets.WORK_DIR }} && docker compose pull && docker compose up -d && exit'
                  host: ${{ secrets.HOST }}
                  user: root
                  key: ${{ secrets.PRIVATE_KEY }}
                  args: -tt
